### ISSUE TITLE
Return multiple middlewares in ::create()

### ISSUE THREAD

**Issue by jimbojsb** [oscarotero/psr7-middlewares#34]
It'd be cool if in the closure for ::create() i could return an array of middlewares instead of just one new one. Example use case would be something like 

``` php
Middleware::create("/admin", function() {
    return [
        new AuthMiddleware(),
        new AdminMiddleware()
    ];
}
```

**Comment by oscarotero** [comment]
This can be done using a library like [psr7-middleware-stack](https://github.com/schnittstabil/psr7-middleware-stack) that creates a middleware component in which you can add more components. Example:

``` php
Middleware::create('/admin', function () {
    return (new MiddlewareStack())
        ->add(new AuthMiddleware())
        ->add(new AdminMiddleware())
});
```

I think Relay has not this feature (allow to use the dispatcher as a middleware component), but should be great.
Anyway, this feature cannot be implemented in this package because it requires to create a middleware dispatcher that is out of its scope.
