### ISSUE TITLE
Does this project follow semver?

### ISSUE THREAD

**Issue by adear11** [oscarotero/psr7-middlewares#37]
I'm just wondering if this project follows semantic versioning?

I ask because in version 3.14 there was a changed introduced in the Honeypot middleware that caused the default behavior of the middleware to change. 

This change caused the contact form on my website to stop working.

I only ask because if it doesn't, I need to lock my composer version to a specific version rather than doing the "standard" ^3.0 in composer. Following semantic versioning, I would not have expected to have what is in actuality a BC break when going from 3.13.1 to 3.16.1.

Thanks for this library. I really like it.

**Comment by oscarotero** [comment]
Hello @adear11 
Yes, I know that some "minor changes" in 3.x versions introduced breaking BC, and sorry by that. This is due this project started as something more experimental, but because its increasing popularity, I've started to follow semver from 3.14. So you can configure composer safety to "^3.14".

**Comment by adear11** [comment]
Thanks. I appreciate the info.
